############## PETUNJUK ORIENTASI ################
# hadap depan [0.0]
# hadap kiri [1.5708]
# hadap kanan [-1.5708]
# hadap belakang [3.14]
##################################################

# RUANG TF (Teaching Factory)
Posisi_Awal:  # tanda lakban hitam
  wp1: [0.687, 0.272, 0.0]

Depan_Raisa:
  wp1: [3.82, 2.77, 1.5708]

Depan_3D_Print:
  wp1: [4.9, -5.51, 0.0]
