############## PETUNJUK ORIENTASI ################
# hadap depan [0.0]
# hadap kiri [1.5708]
# hadap kanan [-1.5708]
# hadap belakang [3.14]
##################################################

# Posisi_Awal:
#   wp1: [0.979, 0.0764, 0.0]

Ruang_5G:
  wp1: [16.1, 0.126, 1.5708]
  wp2: [15.8, 2.69, 1.5708]

Ruang_Kantor:
  wp1: [37.6, -0.223, 1.5708]
  wp2: [37.7, 1.73, 1.5708]
